# Site settings
title: The Schmear Campaign
email: letsnosh@theschmearcampaign.com
description: "Occasional dispatches from Bageldom"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.theschmearcampaign.com" # the base hostname & protocol for your site

ratingscale:
  - Disappointing
  - Meh
  - Decent
  - Good
  - Life-changing

destination: _public

gems: ['jekyll-offline']

# Build settings
markdown: kramdown

prose:
  rooturl: "_posts"
